#ifndef QTPD_UI_LIBRARY_GLOBAL_H
#define QTPD_UI_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTPD_UI_LIBRARY_LIBRARY)
#  define QTPD_UI_LIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTPD_UI_LIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTPD_UI_LIBRARY_GLOBAL_H
